### ISSUE TITLE
Eclipse JKube - Java scenarios for Kuberenetes

### ISSUE THREAD

**Issue by manusa** [killercoda/scenarios-kubernetes#1]
Hi,

I'm a maintainer of the [Eclipse JKube project](https://github.com/eclipse/jkube). JKube is a set of Gradle and Maven plugins that simplify the task of deploying a Java application into Kubernetes. It covers the all of the required steps: container image generation, resource manifest generation, resource manifest deployment, and so on.

We're currently hosting a few getting started [scenarios](https://github.com/jkubeio/katacoda-scenarios) for our plugins at [KataCoda](https://katacoda.com/jkubeio/).

As you probably know, KataCoda is [shutting down](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html) next month (June 2022). I was wondering if we could host our actual (or even a few more) scenarios in your platform, nad if this repo / [section](https://killercoda.com/kubernetes) would be a good fit for them.

**Comment by wuestkamp** [comment]
It would probably be best if you just create a new account on killercoda.com and link your existing Github repo to it.
Then you could have killercoda.com/jkube or /kubeio as before on Katacoda.

Here is described how you to do this: https://killercoda.com/creators/get-started
